name: openapi
version: 1.0.0
description: OpenAPI API client
homepage: homepage


environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  dio: '^5.7.0'
  one_of: '>=1.5.0 <2.0.0'
  one_of_serializer: '>=1.5.0 <2.0.0'
  built_value: ^8.1.0
  built_collection: ^5.1.0
  json_annotation: ^4.8.0

dev_dependencies:
  built_value_generator: ^8.1.3
  build_runner: ^2.4.0
  test: '^1.16.0'
  json_serializable: ^6.6.0
